openapi: 3.0.3
info:
  title: Leo Vegas Wallet API
  description: Leo Vegas assessment
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /player/currentBalance:
    get:
      tags:
        - Player
      parameters:
        - name: 'playerId'
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: player id
          example: 333
      responses:
        '200':
          $ref: '#/components/responses/PlayerBalance'
        '400':
          description: 'Bad request'
        '404':
          description: 'Player not found'
        '500':
          description: 'Server error'
  /transaction/create:
    post:
      tags:
        - Transaction
      requestBody:
        description: Create transaction request
        required: true
        content:
          application/json:
            schema:
              properties:
                playerId:
                  type: number
                  format: int64
                type:
                  type: string
                amount:
                  type: number
                  format: double
      responses:
        '201':
          description: 'Created'
        '400':
          description: 'Bad request'
        '500':
          description: 'Server error'
  /transaction/playerHistory:
    get:
      tags:
        - Transaction
      parameters:
        - name: 'playerId'
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: player id
          example: 333
      responses:
        '200':
          $ref: '#/components/responses/PlayerTransactionHistoryArray'
        '400':
          description: 'Bad request'
        '500':
          description: 'Server error'
components:
  responses:
    PlayerBalance:
      description: Player current balance
      content:
        application/json:
          schema:
            type: object
            properties:
              currentBalance:
                type: number
                format: double
    PlayerTransactionHistoryArray:
      description: Player transaction history response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PlayerTransactionHistory'
  schemas:
    PlayerTransactionHistory:
      type: object
      properties:
        playerName:
          type: string
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      properties:
        type:
          type: string
        amount:
          type: number
          format: double

